name: trunk check
on: [push, workflow_dispatch]
jobs:
  trunk_check:
    name: trunk check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all